### ISSUE TITLE
eastar vs :digraph

### ISSUE THREAD

**Issue by Trevoke** [herenowcoder/eastar#4]
Hi,

What benefits does this bring over http://erlang.org/doc/man/digraph.html#get_short_path-3 ?

**Comment by wkhere** [comment]
Hi,
several reasons.

* I have no idea how to represent weighted edges in `:digraph` - maybe you know? They have some labels but not weights
* not sure if `get_short_path` really implements A* - [look at the source](https://github.com/erlang/otp/blob/master/lib/stdlib/src/digraph.erl#L611-L640)
* I wanted to have very abstract graphs - in `eastar` you pass functions which define neighbors, distances and H-function (estimate-to-goal) instead of concrete data and it's exactly what I needed in a consumer of this lib
* my impl has a data structure for priority queue which allows for O(logN) delete-by-value, which is non-standard for typical p. queue but is needed in A* (to be very precise either delete-by-value or update-priority-for-value is needed in this algo)

HTH
